version: '3.5'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scopely-server
    env_file:
      - "./.env"
    volumes:
      - ./src:/app/src
    ports:
      - "8080:8080"
    networks:
      - scopely-network
    depends_on:
      - postgres

  postgres:
    container_name: scopely-postgres
    image: postgres:latest
    env_file:
      - "./.env"
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - scopely-network
    restart: unless-stopped

networks:
  scopely-network:
    driver: bridge

volumes:
  postgres: